#
# Makefile for the RDA device drivers.
#

obj-$(CONFIG_MMC_RDA)		+= rda_mmc.o md.o md_sys.o rda_regulator.o ifc.o cpu.o pm_ddr.o OrangePi_GPIOC.o
obj-$(CONFIG_ARM_RDA_CPUFREQ)     	+= rda-cpufreq.o

obj-$(CONFIG_CLK_RDA)	+= clk_rda.o clk_ops_rda.o ap_clk.o

obj-$(CONFIG_RDA_NET_SUPPORT)		+= i2c-rda.o net/


