#
# Makefile for the RDA device drivers.
#

obj-$(CONFIG_MMC_RDA)		+= rda_mmc.o md.o md_sys.o rda_regulator.o ifc.o cpu.o pm_ddr.o rda-gpio_old.o rda-cpufreq.o i2c-rda.o cpuidle.o

obj-$(CONFIG_CLK_RDA)	+= clk_rda.o clk_ops_rda.o ap_clk.o

obj-$(CONFIG_RDA_NET_SUPPORT)		+= net/

obj-$(CONFIG_VIDEO_RDA)             += media/


